site_name: hcoco1

nav:
  - Home:
      - Overview: 'index.md'
  - Elevator Pitch:
      - Videos & Audios: 'pitch.md'
  - Non Technical Questions:
      - General: 'questions.md'
      - STAR Method: 'star.md'
      - Interview 1: interview.md
      - Resume: 'resume.md'
  - Technical Questions:
      - Javascript:
          - Fundamentals: 'vanilla.md'
          - Basic: 'js_basic.md'
          - Intermediate: 'js_intermediate.md'
          - Arrays: 'arrays.md'
      - React: 'react.md'
      - Python: 'python.md'
      - Cybersecurity:
          - Asset and Inventory: 'assest_cyber.md'
          - Network Systems: 'system.md'
      - AWS: 'aws.md'

theme:
  name: 'readthedocs'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

docs_dir: 'docs'



