site_name: hcoco1

nav:
  - Home:
      - Overview: 'index.md'
      - Elevator Pitch: 'pitch.md'
  - Non Technical Questions:
      - General: 'questions.md'
      - STAR Method: 'star.md'
  - Technical Questions:
      - Js (Vanilla): 'vanilla.md'
      - React: 'react.md'
      - Python: 'python.md'
      - Cybersecurity:
          - Asset and Inventory: 'assest_cyber.md'
          - Network Systems: 'system.md'
      - AWS: 'aws.md'

theme:
  name: 'readthedocs'


docs_dir: 'docs'

